### ISSUE TITLE
example tag templates require extra step

### ISSUE THREAD

**Issue by ajcrutch** [marcjwo/cloud-bi-fabric#2]
Tried to use tag templates verbatim and got this error

```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Optional object type attributes are experimental

  on variables.tf line 53:
  53: variable "tag_templates" {

This feature is currently an opt-in experiment, subject to change in future
releases based on feedback.

Activate the feature for this module by adding module_variable_optional_attrs
to the list of active experiments.
```

I am having trouble finding where to add something like 
```
terraform {
  experiments = [module_variable_optional_attrs]
}
```
...as was suggested [here](https://github.com/hashicorp/terraform/issues/24147#issuecomment-587961724).

**Comment by ajcrutch** [comment]
Actually I was able to resolve this myself, by adding 

```
terraform {
  experiments = [module_variable_optional_attrs]
}
```

to...
cloud-bi-fabric/variables.tf
and modules/datacatalog/variables.tf

I made a PR here https://github.com/marcjwo/cloud-bi-fabric/pull/3

**Comment by marcjwo** [comment]
This is not required when using a terraform version => 1.3.0 - will highlight that in the readme. Thank you!
